### ISSUE TITLE
[返信機能] ダッシュボードから投稿されたDeveloerCommentを保存する

### ISSUE THREAD

**Issue by himaratsu** [meyasubaco/dashboard-api#81]
[ユーザーからのコメント](https://github.com/meyasubaco/user-api/issues/37) に対して、デベロッパーはダッシュボードから返信する。

# 処理の流れ概要

* 送信する情報
 * thread_id
 * content
* thread_id はどのスレッドに対するコメントか？を表すもの
* DeveloperComment は必ずユーザーへの返信の形になるので、thread_id は必須

# Backend側のフロー

## DeveloperComment の投稿

* thread_id, content があるか確認
* thread_id からスレッド情報を引く
* DeveloperCommentを新規作成
* DeveloperCommentを保存
* スレッド情報の「最終更新」の情報を上書きして保存
 * lastCommentContent
 * lastCommentUpdateTime
 * lastCommentPoster (= "developer")
 * lastDeveloperShowTime
 * developerReplied (= true)

## Thread 一覧の取得

* Application ID から、そのアプリに紐付いたスレッドの一覧を取得する
 * 最終コメント更新日が新しい順に並んでいる
* スレッド一覧は次の情報をもつ
 * Thread 情報 （最後のコメントの内容や、最終更新時刻）
  * デベロッパーから見た未読/既読情報も Bool で返す
  * これは lastDeveloperShowTime と lastCommentUpdateTime を比較し、lastCommentPoster が自分でないことを確認して計算する
 * AppliUser（そのスレッドで相手するのは、どのアプリユーザーなのか？）

## Comment 一覧の取得

* スレッドのコメント一覧表示のためのAPI
* Comments （そのスレッドに投稿されたコメントの一覧）
 * Comments とは UserComments と DeveloperComments を混ぜたもの
 * 20件ずつくらいを取得して、混ぜて、日付順にソートして返す
* ページング必要

# イメージ図

![image](https://cloud.githubusercontent.com/assets/1206009/13031655/62665d0c-d318-11e5-916a-1f2356b3d1e9.png)

**Comment by shoma2da** [comment]
Closeします
