### ISSUE TITLE
課金状況を返すAPIにTrialとFreeを追加する

### ISSUE THREAD

**Issue by shibe97** [meyasubaco/dashboard-api#94]
https://github.com/meyasubaco/dashboard-ui/issues/125

## 概要
固定でproのみ返ってくるところをTrial、またはFreeとして返ってくるようにしてほしい。
ついでにpro -> Proにしてほしい

**Comment by himaratsu** [comment]
現在の仕様

* ユーザーを作成したときに Payment は作られない
* 課金のエンドポイントに POST した時にはじめて Payment が DB に書かれる

**Comment by himaratsu** [comment]
＜今後の方針＞

* ユーザー新規登録時に、Paymentを作成する。planNameは`Trial`
* 毎日バッチを回して、Paymentが発行されてから3ヵ月以上経過してるレコードは`Free`に書き換える
* 決済したユーザーについては planName を `Pro` に書き換える
  * この時に PaymentHistory も更新する

**Comment by himaratsu** [comment]
@shoma2da ↑こんな感じで考えました。微妙に複雑なので、どっかで口頭で相談させてください！

**Comment by shoma2da** [comment]
良いと思います！詳細はまた別途。

**Comment by shoma2da** [comment]
done
